--------------------------------------------------------
-- Archivo creado  - viernes-octubre-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAPTURAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DGOMEZ"."CAPTURAS_SEQ"  MINVALUE 1000 MAXVALUE 2000 INCREMENT BY 1 START WITH 1040 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DELITOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DGOMEZ"."DELITOS_SEQ"  MINVALUE 100 MAXVALUE 200 INCREMENT BY 1 START WITH 120 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CAPTURAS
--------------------------------------------------------

  CREATE TABLE "DGOMEZ"."CAPTURAS" 
   (	"ID" NUMBER(*,0), 
	"FECHA" TIMESTAMP (6), 
	"DEPARTAMENTO" VARCHAR2(255 BYTE), 
	"MUNICIPIO" VARCHAR2(255 BYTE), 
	"DIA" VARCHAR2(255 BYTE), 
	"BARRIO" VARCHAR2(255 BYTE), 
	"ZONA" VARCHAR2(255 BYTE), 
	"CLASE_SITIO" VARCHAR2(255 BYTE), 
	"EDAD" NUMBER(*,0), 
	"SEXO" VARCHAR2(255 BYTE), 
	"ESTADO_CIVIL" VARCHAR2(255 BYTE), 
	"CLASE_EMPLEADO" VARCHAR2(255 BYTE), 
	"PROFESION" VARCHAR2(255 BYTE), 
	"ESCOLARIDAD" VARCHAR2(255 BYTE), 
	"DELITO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table DELITOS
--------------------------------------------------------

  CREATE TABLE "DGOMEZ"."DELITOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
REM INSERTING into DGOMEZ.CAPTURAS
SET DEFINE OFF;
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1005',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','ARJONA','Lunes','PERIMETRO RURAL','RURAL','CARRETERA','37','MASCULINO','UNION LIBRE','INDEPENDIENTE','INGENIERO','0','100');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1006',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','ARJONA','Lunes','BARRIO SUEÑOS DE LIBERTAD','URBANA','VIAS PUBLICAS','18','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1007',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','CARTAGENA (CT)','Lunes','SAN PEDRO MARTIR','URBANA','VIAS PUBLICAS','37','MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR','0','0','103');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1008',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','CARTAGENA (CT)','Lunes','LA BOQUILLA','RURAL','AEROPUERTO','37','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','106');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1009',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','CARTAGENA (CT)','Lunes','LA ESPERANZA','URBANA','VIAS PUBLICAS','28','MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1010',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','CARTAGENA (CT)','Lunes','CTO. BARU','URBANA','PLAYA','31','MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1011',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','MOMPÓS','Lunes','BARRIO LA TERRITORIAL','URBANA','VIAS PUBLICAS','38','MASCULINO','CASADO','INDEPENDIENTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1012',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','SAN JACINTO','Lunes','SECTOR SIETE DE AGOSTO','URBANA','VIAS PUBLICAS','25','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','107');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1013',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOLÍVAR','SAN JUAN NEPOMUCENO','Lunes','SECTOR COSTA DE ORO','URBANA','VIAS PUBLICAS','21','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1014',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','BUENAVISTA','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS','36','MASCULINO','SOLTERO','COMERCIANTE','0','0','108');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1015',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS','17','MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1016',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS','19','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1017',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS','20','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1018',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS','21','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1019',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','CIÉNEGA','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS','20','MASCULINO','UNION LIBRE','ESTUDIANTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1020',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','DUITAMA','Lunes','SAN FERNANDO','URBANA','VIAS PUBLICAS','23','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','108');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1021',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','DUITAMA','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS','33','MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1022',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','GACHANTIVÁ','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS','22','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1023',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','SOATÁ','Lunes','EL CENTRO','URBANA','VIAS PUBLICAS','19','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1024',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'BOYACÁ','TUNJA (CT)','Lunes','VDA.TRAS DEL ALTO','RURAL','TRAMO DE VIA','37','MASCULINO','UNION LIBRE','AGRICULTOR','0','0','102');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1025',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','ANSERMA','Lunes','AVENIDA LIBERTADOR','URBANA','VIAS PUBLICAS','32','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1026',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','CHINCHINÁ','Lunes','LA NUBIA','URBANA','VIAS PUBLICAS','52','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','105');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1027',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','CHINCHINÁ','Lunes','PANORAMA','URBANA','VIAS PUBLICAS','39','MASCULINO','SOLTERO','DESEMPLEADO','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1028',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANIZALES (CT)','Lunes','BARRIO CHIPRE','URBANA','CASAS DE HABITACION','58','MASCULINO','CASADO','COMERCIANTE','0','0','106');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1029',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANIZALES (CT)','Lunes','KENNEDY','URBANA','VIAS PUBLICAS','25','FEMENINO','SOLTERO','INDEPENDIENTE','0','0','104');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1030',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANIZALES (CT)','Lunes','SOLFERINO','URBANA','VIAS PUBLICAS','22','MASCULINO','SOLTERO','DESEMPLEADO','0','0','109');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1031',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANIZALES (CT)','Lunes','CENTRO','URBANA','VIAS PUBLICAS','44','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','104');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1032',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANIZALES (CT)','Lunes','PUERTA DEL SOL','URBANA','VIAS PUBLICAS','22','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','104');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1033',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANZANARES','Lunes','CENTRO','URBANA','VIAS PUBLICAS','59','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','101');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1034',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANZANARES','Lunes','CENTRO','URBANA','VIAS PUBLICAS','20','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','104');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1035',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANZANARES','Lunes','LOMBO','URBANA','VIAS PUBLICAS','26','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','107');
Insert into DGOMEZ.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values ('1036',to_timestamp('01/01/18 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'CALDAS','MANZANARES','Lunes','CENTRO','URBANA','VIAS PUBLICAS','46','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','101');
REM INSERTING into DGOMEZ.DELITOS
SET DEFINE OFF;
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('100','ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE DE TRÁNSITO)');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('101','ARTÍCULO 111. LESIONES PERSONALES');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('102','ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE DE TRANSITO )');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('103','ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('104','ARTÍCULO 265. DAÑO EN BIEN AJENO');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('105','ARTÍCULO 365. FABRICACIÓN -  TRÁFICO -  PORTE O TENENCIA DE ARMAS DE FUEGO - ACCESORIOS -  PARTES O MUNICIONES');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('106','ARTÍCULO 376. TRÁFICO -  FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('107','ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('108','ARTÍCULO 447. RECEPTACIÓN');
Insert into DGOMEZ.DELITOS (ID,NOMBRE) values ('109','ARTÍCULO 448. FUGA DE PRESOS');
--------------------------------------------------------
--  DDL for Index SYS_C006994
--------------------------------------------------------

  CREATE UNIQUE INDEX "DGOMEZ"."SYS_C006994" ON "DGOMEZ"."DELITOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006997
--------------------------------------------------------

  CREATE UNIQUE INDEX "DGOMEZ"."SYS_C006997" ON "DGOMEZ"."CAPTURAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  Constraints for Table CAPTURAS
--------------------------------------------------------

  ALTER TABLE "DGOMEZ"."CAPTURAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DELITOS
--------------------------------------------------------

  ALTER TABLE "DGOMEZ"."DELITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAPTURAS
--------------------------------------------------------

  ALTER TABLE "DGOMEZ"."CAPTURAS" ADD FOREIGN KEY ("DELITO_ID")
	  REFERENCES "DGOMEZ"."DELITOS" ("ID") ENABLE;
