create tablespace  mid_term
datafile 'mid_term.dbf' size 40M;

CREATE USER dgomez IDENTIFIED BY dgomez
DEFAULT TABLESPACE mid_term 
QUOTA UNLIMITED ON mid_term;

CREATE ROLE MINI_DBA;
GRANT CREATE SEQUENCE TO MINI_DBA;

CREATE ROLE STUDENT;
GRANT CONNECT TO STUDENT;
GRANT MINI_DBA TO STUDENT;

GRANT MINI_DBA TO dgomez;